version: "3.8"
services:
  mongodb:
    build: ./mongodb
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME:admin
      - MONGO_iNITDB_ROOT_PASSWORD:password
